### PR TITLE
Respect setParent calls for noop subsegments.

### LINKED ISSUE #213: Subsegment cannot be found on 2.7.1 / AWS Lambda
After upgrading from 2.6.1 to 2.7.1, the following error appeared when opening the first subsegment using this code:

```java
AWSXRay.createSubsegment("init dagger component", () -> { /* ... */ });
```

```
Failed to end a subsegment: subsegment cannot be found.: com.amazonaws.xray.exceptions.SubsegmentNotFoundException
com.amazonaws.xray.exceptions.SubsegmentNotFoundException: Failed to end a subsegment: subsegment cannot be found.
	at com.amazonaws.xray.contexts.LambdaSegmentContext.endSubsegment(LambdaSegmentContext.java:136)
	at com.amazonaws.xray.AWSXRayRecorder.endSubsegment(AWSXRayRecorder.java:612)
	at com.amazonaws.xray.AWSXRayRecorder.createSubsegment(AWSXRayRecorder.java:389)
	at com.amazonaws.xray.AWSXRay.createSubsegment(AWSXRay.java:92)
	at <my handler>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
```

I am using Java 11 (Corretto) on AWS Lambda.

### PR DESCRIPTION
**Pull request by anuraaga**
Fixes #213

I mistook that the parent and parent segment are the same. The API is crufty in setting the parent after construction, even though it's a constant, that could be another improvement for a major version. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java [hunk 1]
```diff
@@ -59,55 +58,71 @@ public void setupAWSXRay() {
...
+    @SetEnvironmentVariable(key = "_X_AMZN_TRACE_ID", value = MALFORMED_TRACE_HEADER)
+    void testBeginSubsegmentWithCompleteButMalformedTraceHeaderEnvironmentVariableResultsInAFacadeSegmentParent() {
+        testContextResultsInFacadeSegmentParent();
     }
 
     @Test
-    public void testLeakedSubsegmentsAreCleanedBetweenInvocations() {
-
+    @SetEnvironmentVariable(key = "_X_AMZN_TRACE_ID", value = TRACE_HEADER_2)
+    void testNotSampledSetsParentToSubsegment() {
```
Comment (anuraaga) [inline aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java:85]: This is the new test, the rest are refactoring to replace powermock with junit5 extension

File: aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java [hunk 2]
```diff
@@ -59,55 +58,71 @@ public void setupAWSXRay() {
     }
 
     @Test
-    public void testBeginSubsegmentWithNullTraceHeaderEnvironmentVariableResultsInADummySegmentParent() {
-        testMockContext(TraceHeader.fromString(null), FacadeSegment.class);
+    void testBeginSubsegmentWithNullTraceHeaderEnvironmentVariableResultsInADummySegmentParent() {
```
Comment (willarmiros) [inline aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java:61]: I know this is mostly out of scope for the PR, but the name of this test isn't right. The name says we expect a Dummy (no-op) segment whereas what we test for/actually get is a facade segment. 

I'm pretty sure contrary to the name of the test always using a facade segment is the behavior we want, and we can have a larger discussion if anyone on team disagrees, but for now renaming the test to avoid future confusion would be nice.

File: aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java [hunk 3]
```diff
@@ -59,55 +58,71 @@ public void setupAWSXRay() {
...
+        testContextResultsInFacadeSegmentParent();
     }
 
     @Test
-    public void testBeginSubsegmentWithIncompleteTraceHeaderEnvironmentVariableResultsInADummySegmentParent() {
-        testMockContext(TraceHeader.fromString("a"), FacadeSegment.class);
+    @SetEnvironmentVariable(key = "_X_AMZN_TRACE_ID", value = "a")
+    void testBeginSubsegmentWithIncompleteTraceHeaderEnvironmentVariableResultsInADummySegmentParent() {
```
Comment (willarmiros) [inline aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java:67]: Ditto on renaming

**Review by willarmiros — APPROVED** [review]
Just noticed your branch name and 🤣

File: aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java (hunk 2 above)
Comment (anuraaga) [reply aws-xray-recorder-sdk-core/src/test/java/com/amazonaws/xray/contexts/LambdaSegmentContextTest.java]: Thanks - yeah good cleanup
